[platformio]
default_envs = esp32s3_lstm

[env:esp32s3_lstm]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
monitor_speed = 115200
board_build.partitions = partitions.csv
extra_scripts = extra_script.py
build_flags =
  -D CORE_DEBUG_LEVEL=0
  -O3
  -D CONFIG_NN_OPTIMIZED
  -D CONFIG_IDF_TARGET_ESP32S3
  -D ARCH_ESP32_S3=1
  -I lib/esp-nn/include
  -I lib/esp-nn/src/common
  -mlongcalls
build_unflags = -Os
lib_ldf_mode = deep+
monitor_filters = esp32_exception_decoder
