#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import struct
from pathlib import Path

MAGIC = 0x4D4C4952


def parse_rilm(path: Path):
    data = path.read_bytes()
    off = 0
    magic, = struct.unpack_from('<I', data, off); off += 4
    if magic != MAGIC:
        raise ValueError(f'bad RILM magic 0x{magic:08x}')
    version, = struct.unpack_from('<H', data, off); off += 2
    off += 2
    count, = struct.unpack_from('<I', data, off); off += 4
    tensors = {}
    for _ in range(count):
        name_len, = struct.unpack_from('<H', data, off); off += 2
        name = data[off:off + name_len].decode('utf-8'); off += name_len
        dtype = data[off]; off += 1
        ndim = data[off]; off += 1
        dims = struct.unpack_from('<' + 'I' * ndim, data, off); off += 4 * ndim
        scale, = struct.unpack_from('<f', data, off); off += 4
        payload_len, = struct.unpack_from('<I', data, off); off += 4
        payload = data[off:off + payload_len]; off += payload_len
        tensors[name] = (dtype, dims, scale, payload)
    return version, tensors, hashlib.sha256(data).hexdigest()


def c_float_literal(v: float) -> str:
    s = f'{v:.9g}'
    if 'e' not in s and 'E' not in s and '.' not in s:
        s += '.0'
    return s + 'f'


def c_bytes(name: str, payload: bytes) -> str:
    lines = [f'alignas(16) static constexpr uint8_t {name}[] = {{']
    for i in range(0, len(payload), 16):
        chunk = payload[i:i + 16]
        lines.append('  ' + ', '.join(str(b) for b in chunk) + ',')
    lines.append('};')
    return '\n'.join(lines)


def c_floats(name: str, payload: bytes) -> str:
    vals = struct.unpack('<' + 'f' * (len(payload) // 4), payload)
    lines = [f'alignas(16) static constexpr float {name}[] = {{']
    for i in range(0, len(vals), 8):
        lines.append('  ' + ', '.join(c_float_literal(v) for v in vals[i:i + 8]) + ',')
    lines.append('};')
    return '\n'.join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description='Export the tiny FC output head as a C++ header for sharded workers.')
    ap.add_argument('--weights', default='weights_p12_h256_backup_770ed901.bin')
    ap.add_argument('--out', default='src/fc_shard_weights.h')
    args = ap.parse_args()
    root = Path(__file__).resolve().parents[1]
    weights = Path(args.weights)
    if not weights.is_absolute():
        weights = root / weights
    out = Path(args.out)
    if not out.is_absolute():
        out = root / out

    version, tensors, sha = parse_rilm(weights)
    fcw_dtype, fcw_dims, fcw_scale, fcw_payload = tensors['fc.weight']
    fcb_dtype, fcb_dims, fcb_scale, fcb_payload = tensors['fc.bias']
    if fcw_dtype != 1:
        raise ValueError(f'expected int8 fc.weight, got dtype={fcw_dtype}')
    if fcb_dtype != 0:
        raise ValueError(f'expected f32 fc.bias, got dtype={fcb_dtype}')
    if len(fcw_dims) != 2 or len(fcb_dims) != 1 or fcw_dims[0] != fcb_dims[0]:
        raise ValueError(f'bad fc shapes: fcw={fcw_dims} fcb={fcb_dims}')

    content = f'''#pragma once
#include <stdint.h>
#include <stddef.h>

// Generated by tools/export_fc_shard_header.py from {weights.name}
// RILM v{version} sha256={sha}
static constexpr uint32_t RI_FC_ROWS = {fcw_dims[0]};
static constexpr uint32_t RI_FC_COLS = {fcw_dims[1]};
static constexpr float RI_FC_WEIGHT_SCALE = {c_float_literal(fcw_scale)};
static constexpr float RI_FC_BIAS_SCALE = {c_float_literal(fcb_scale)};
static constexpr const char *RI_FC_WEIGHTS_SHA256 = "{sha}";

{c_bytes('RI_FC_WEIGHT_Q8', fcw_payload)}

{c_floats('RI_FC_BIAS_F32', fcb_payload)}
'''
    out.write_text(content)
    print(f'wrote {out} rows={fcw_dims[0]} cols={fcw_dims[1]} sha256={sha}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
